title = "home hosts"

# [[hosts]]
# name = "nixos"
# module = "/nixos/host.tower/configuration.nix"

[[hosts]]
name = "tower"
module = "/nixos/host.tower2/configuration.nix"

[[hosts]]
name = "nixos"
module = "/nixos/host.laptop/configuration.nix"
